services:
  app:
    build: .
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - .env.prod
    environment:
      ADMIN_ENV_FILE: /app/.env.runtime
    volumes:
      - ./.env.prod:/app/.env.runtime
      - ./logs:/app/logs
      - /var/lib/detilda/_workdir:/app/_workdir
    restart: unless-stopped
